#!/usr/bin/env node

var exec = require('child_process').execFile
  , path = require('path')
  , fs = require('fs')

  , provisions = require('./src/provisions')

  , baseDir = path.join(__dirname, '..')

  , conf = require('./config')

process.env.BASEDIR = baseDir
process.env.KEYCHAIN_LOCATION = conf.keychain.path
process.env.KEYCHAIN_PASSWORD = conf.keychain.password

var jobs =
    [ parseProvisions
    , installProvisions
    , addKeychain
    , unlockKeychain
    , buildTarget
    , clean
    ]
  , nextJob = 0

executeNextJob()

function executeNextJob(err) {
	if(jobs.length > nextJob) {
		jobs[nextJob++](executeNextJob)
	}
}

function parseProvisions(done) {
	provisions.parse(conf.provisions, function(err, parsedProvisions) {
		conf.parsedProvisions = parsedProvisions
		done()
	})
}

function installProvisions(done) {
	conf.installedProvisions = provisions.install(conf.parsedProvisions)
	done()
}

function addKeychain(done) {
	exec(
	  'security'
	, [ 'default-keychain'
	  , '-s'
	  , conf.keychain.path
	  ]
	, done
	)
}

function unlockKeychain(done) {
	exec(
	  'security'
	, [ 'unlock-keychain'
	  , '-p'
	  , conf.keychain.password
	  , conf.keychain.path
	  ]
	, done
	)
}

function buildTarget(done) {
	utils.recurMkdirSync(conf.build.output)
	exec(
	  'xcodebuild'
	, [ '-target'
	  , conf.build.target
	  , '-configuration'
	  , conf.build.configuration
	  , 'SYMROOT'
	  , conf.build.output
	  , 'clean'
	  , 'build'
	  ]
	, done
	)
}

function clean(done) {
	provisions.clean(conf.installedProvisions)
	done()
}
